version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update this URL to point to your API environment
        VITE_API_URL: http://localhost:5117
    image: spendinganalyzer-web:latest
    ports:
      - '5173:80'
    environment:
      - NODE_ENV=production